/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package raportdigital;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Guru extends javax.swing.JFrame {
private final Connection Connection;

    /**
     * Creates new form Guru
     */
    public Guru() throws SQLException {
        this.Connection = DatabaseConnection.getConnection();
        initComponents();
        tampilkanguru(tabelguru);
        id_auto();
        nipp.setEditable(false);
        namaguru.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nipp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        namaguru = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jeniskelamin = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        mapel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelguru = new javax.swing.JTable();
        insert = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Input Guru");

        jLabel2.setText("NIP");

        jLabel3.setText("Nama");

        jLabel4.setText("Jenis Kelamin");

        jeniskelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L", "P" }));

        jLabel5.setText("Mata Pelajaran");

        tabelguru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelguru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelguruMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelguru);

        insert.setText("Insert");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jeniskelamin, 0, 94, Short.MAX_VALUE)
                                    .addComponent(namaguru)
                                    .addComponent(nipp)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(insert)
                                .addComponent(update))
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(mapel, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(delete)
                                    .addComponent(clear))))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(nipp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(namaguru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jeniskelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(mapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insert)
                            .addComponent(delete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(update)
                            .addComponent(clear)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        // TODO add your handling code here:
        try{
        String nnip = nipp.getText();
        String nama = namaguru.getText();
        String jk = (String) jeniskelamin.getSelectedItem();
        String mata = mapel.getText();
        
        Connection connection = DatabaseConnection.getConnection();
        
        String sql = "Insert into guru (nip, nama_guru, jenis_kelamin_guru, mata_pelajaran) "
                    + "Values (?,?,?,?)";
        PreparedStatement ps = connection.prepareStatement(sql);
        ps.setString(1,nnip);
        ps.setString(2, nama);
        ps.setString(3, jk);
        ps.setString(4, mata);
        
        ps.executeUpdate();
        
        nipp.setText("");
        namaguru.setText("");
        mapel.setText("");
        id_auto();
        
        JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan!");
        tampilkanguru(tabelguru);
        
        }catch(SQLException e){
            e.printStackTrace();
            JOptionPane.showConfirmDialog(null, "Error" + e.getMessage());
        }
    }//GEN-LAST:event_insertActionPerformed
    
    public final void id_auto() {
        try {
            final Statement stat = Connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            final String sql = "select max (cast(substring(nip, 2,4)as integer)) as no from guru";
            final ResultSet rs = stat.executeQuery(sql);
            while (rs.next()) {
                if (rs.getInt("no") == 0) {
                    nipp.setText("G0001");
                } else {
                    int set_id = rs.getInt("no") + 1;
                    String no = String.valueOf(set_id);
                    while (no.length() < 4) {
                        no = "0" + no;
                    }
                    nipp.setText("G" + no);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Siswa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void tabelguruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelguruMouseClicked
        // TODO add your handling code here:
        int row = tabelguru.getSelectedRow();
        nipp.setText(tabelguru.getValueAt(row, 0).toString());
        namaguru.setText(tabelguru.getValueAt(row, 1).toString());
        jeniskelamin.setSelectedItem(tabelguru.getValueAt(row, 2).toString());
        mapel.setText(tabelguru.getValueAt(row, 3).toString());
    }//GEN-LAST:event_tabelguruMouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:    
        try {
            String nnip = !nipp.getText().trim().isEmpty() ? nipp.getText().trim() : tabelguru.getValueAt(tabelguru.getSelectedRow(), 0).toString();
            String sql = "delete from guru where nip = ?";
            PreparedStatement ps = Connection.prepareStatement(sql);
            ps.setString(1, nnip);
            ps.execute();

            tampilkanguru(tabelguru);
            nipp.setText("");
            namaguru.setText("");
            mapel.setText("");
            id_auto();

            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
        } catch (SQLException ex) {
            Logger.getLogger(Guru.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        nipp.setText("");
        namaguru.setText("");
        mapel.setText("");
        id_auto();
    }//GEN-LAST:event_clearActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        String nnip = nipp.getText();
        String namaguruu = namaguru.getText();
        String jk = (String) jeniskelamin.getSelectedItem();
        String mata = mapel.getText();
        
        try{
            String sql = "Update guru set nama_guru= ?, jenis_kelamin_guru= ?, mata_pelajaran= ? where nip= ?";
            PreparedStatement ps = Connection.prepareStatement(sql);
            ps.setString(1, namaguruu);
            ps.setString(2, jk);
            ps.setString(3, mata);
            ps.setString(4, nnip);
            ps.executeUpdate();
            
            this.id_auto();
            tampilkanguru(tabelguru);
            
            JOptionPane.showMessageDialog(this, "Data berhasil diupdate!");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Data gagal diupdate, karena:" + e.getMessage());
        }
    }//GEN-LAST:event_updateActionPerformed

    private void tampilkanguru(JTable guruTable){
        try{
            String sql = "Select * from guru order by nip";
            PreparedStatement pst = Connection.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            DefaultTableModel model = new DefaultTableModel();
            
            model.addColumn("NIP");
            model.addColumn("Nama Guru");
            model.addColumn("Jenis Kelamin");
            model.addColumn("Mata Pelajaran");
            while(rs.next()){
                Object[] rowData = new Object[4];
                rowData[0] = rs.getString("nip");
                rowData[1] = rs.getString("nama_guru");
                rowData[2] = rs.getString("jenis_kelamin_guru");
                rowData[3] = rs.getString("mata_pelajaran");
                
            model.addRow(rowData);
            }
            tabelguru.setModel(model);
        }catch(SQLException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error" + e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Guru().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Guru.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jeniskelamin;
    private javax.swing.JTextField mapel;
    private javax.swing.JTextField namaguru;
    private javax.swing.JTextField nipp;
    private javax.swing.JTable tabelguru;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
